### ISSUE TITLE
Missing controls comparing to vscode-webview-ui-toolkit

### ISSUE THREAD

**Issue by veredcon** [vscode-elements/elements#153]
Hi,

We would like to adopt this library instead of the deprecated `vscode-webview-ui-toolkit`. 
There are 3 missing controls that we currently use:
`Progress Ring`
`Link`
`Divider`
Is there a plan to implement them?

Thanks!

**Comment by bendera** [comment]
> Is there a plan to implement them?

From now on, there is. (Although, I would use the native `<a>` and `<hr>` .)

**Comment by bendera** [comment]
I thought about this.

Link: I don't see the point of this component. Webview already provides a default style, including the native links. This component has no added value.

Progress Ring: This can be done by the Icon component:
https://vscode-elements.github.io/components/icon/#animated-icons
![image](https://github.com/user-attachments/assets/44bfeac8-683b-4d94-b2fd-b3be5a7cb29f)
`<vscode-icon name="loading" spin spin-duration="1" size="28" style="color: var(--vscode-progressBar-background);"></vscode-icon>`

Divider: 
Actually, it's a `<hr>` element with some CSS customization. There isn't any specific theme variable for the divider color, but `--vscode-widget-border` is okay.

I'm not sure if it's worth introducing new components because of these. What do you think about this?

**Comment by veredcon** [comment]
Hi @bendera 
Yes I agree that Divider and Link is not an issue, it is just for being compatible to what vscode webview toolkit has offered in the past.
The most important to add is the Progress Ring
Thanks for addressing this issue!
