### ISSUE TITLE
Adding typescript support

### ISSUE THREAD

**Issue by veredcon** [vscode-elements/elements#185]
The motivation for adding TypeScript support includes:

- Improved recognition of custom element tags in .tsx files
![image](https://github.com/user-attachments/assets/6a007246-ce1c-48be-9c44-7a9e4599013b)

- Enhanced IntelliSense for component props, allowing for better auto-completion and code insights.
![image](https://github.com/user-attachments/assets/3445c5e6-b18c-4993-8ec8-4dc50ddf4f55)

This would be a valuable enhancement for the library.

**Comment by bendera** [comment]
See #184

**Comment by bendera** [comment]
I failed to fix the element recognition issue with Vite. It can be fixed by changing the `moduleResolution` in the `tsconfig`, but I believe there’s a good reason why the Vite creators are using the current setting, so I wouldn’t modify it. But fortunately, the React wrapper makes this issue irrelevant.
